variable "account" {}
variable "organization" {}
variable "vpc" {}
variable "cluster_name" {}
variable "nrn" {}
variable "np_api_key" {}
variable "tag_selectors" {}
variable "certificate_arn" {}
variable "agent_repos_extra" {}
variable "domain_name" {}
variable "hosted_private_zone_id" {}
variable "hosted_public_zone_id" {}
variable "github_organization" {}
variable "github_installation_id" {}